name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./MiniKratos/configure.sh

  test:
    runs-on: self-hosted

    if:
      paths: 
      - MiniKratos/*

    steps:
    - name: test
      run:	./MiniKratos/build/test_all

  nothing:
    runs-on: self-hosted

    if:
      paths:
      - !MiniKratos/*

    steps:
    - name: report
      run: echo "Nothing to report"
