name: CoreBuild

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./MiniKratos/configure.sh

  test-red:
    runs-on: self-hosted

    steps:
    - name: check-red
      uses: docker://cdssnc/touched-github-action
      with:
        args: "{MiniKratos/Red/**}"
    - name: test-red
      if: success()
      run: echo "Red"

    - name: check-blue
      uses: docker://cdssnc/touched-github-action
      with: 
        args: "{MiniKratos/Blue/**}"
    - name: test-blue
      if: success()
      run: echo "Blue"

  finish:
    runs-on: self-hosted

    steps:
    - name: report
      run: echo "Nothing to report"
