name: CoreBuild

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./MiniKratos/configure.sh

  test:
    needs: build
    runs-on: self-hosted

    steps:
    - name: test-red
      run: ./MiniKratos/build/test_all

  finish:
    needs:  [build, test]
    runs-on: self-hosted

    steps:
    - name: report
      run: echo "Nothing to report"
