name: CoreBuild

on: [push]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./MiniKratos/configure.sh

  test:
    runs-on: self-hosted

    steps:
    - uses: docker://cdssnc/touched-github-action
    - with:
        args: "{MiniKratos/Red/**}"
    - name: test-red

    steps:
    - uses: docker://cdssnc/touched-github-action
    - with: 
        args: "{MiniKratos/Blue/**}"
    - name: test-blue

  finish:
    runs-on: self-hosted

    if:
      paths:
      - !MiniKratos/*

    steps:
    - name: report
      run: echo "Nothing to report"
